<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("For enrollee");
?><?$APPLICATION->IncludeComponent(
	"bitrix:photogallery",
	".default",
	Array(
		"ADDITIONAL_SIGHTS" => array(),
		"ALBUM_PHOTO_THUMBS_SIZE" => "120",
		"BLOG_URL" => "util-photo-blog-s1",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CELL_COUNT" => "0",
		"COMMENTS_COUNT" => "25",
		"COMMENTS_TYPE" => "blog",
		"DATE_TIME_FORMAT_DETAIL" => "d.m.Y",
		"DATE_TIME_FORMAT_SECTION" => "d.m.Y",
		"DISPLAY_AS_RATING" => "rating",
		"DISPLAY_PANEL" => "N",
		"ELEMENTS_PAGE_ELEMENTS" => "50",
		"ELEMENTS_USE_DESC_PAGE" => "Y",
		"ELEMENT_SORT_FIELD" => "name",
		"ELEMENT_SORT_ORDER" => "desc",
		"IBLOCK_ID" => "1",
		"IBLOCK_TYPE" => "photos",
		"JPEG_QUALITY" => "90",
		"JPEG_QUALITY1" => "95",
		"JPEG_QUALITY2" => "95",
		"MAX_VOTE" => "5",
		"ORIGINAL_SIZE" => "1280",
		"PAGE_NAVIGATION_TEMPLATE" => "arrows",
		"PATH_TO_BLOG" => "",
		"PATH_TO_FONT" => "",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"PATH_TO_USER" => "",
		"SECTION_PAGE_ELEMENTS" => "15",
		"SECTION_SORT_BY" => "UF_DATE",
		"SECTION_SORT_ORD" => "DESC",
		"SEF_FOLDER" => "/photo/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array("index"=>"index.php","section"=>"#SECTION_ID#/","section_edit"=>"#SECTION_ID#/action/#ACTION#/","section_edit_icon"=>"#SECTION_ID#/icon/action/#ACTION#/","upload"=>"#SECTION_ID#/action/upload/","detail"=>"#SECTION_ID#/#ELEMENT_ID#/","detail_edit"=>"#SECTION_ID#/#ELEMENT_ID#/action/#ACTION#/","detail_slide_show"=>"#SECTION_ID#/#ELEMENT_ID#/slide_show/","detail_list"=>"list/","search"=>"search/",),
		"SET_TITLE" => "Y",
		"SHOWN_ITEMS_COUNT" => "4",
		"SHOW_LINK_ON_MAIN_PAGE" => array(0=>"id",1=>"shows",2=>"rating",3=>"comments",),
		"SHOW_TAGS" => "Y",
		"SLIDER_COUNT_CELL" => "4",
		"TAGS_COLOR_NEW" => "3E74E6",
		"TAGS_COLOR_OLD" => "C0C0C0",
		"TAGS_FONT_MAX" => "30",
		"TAGS_FONT_MIN" => "10",
		"TAGS_INHERIT" => "Y",
		"TAGS_PAGE_ELEMENTS" => "150",
		"TAGS_PERIOD" => "",
		"TAGS_SHOW_CHAIN" => "Y",
		"TEMPLATE_LIST" => ".default",
		"THUMBNAIL_SIZE" => "90",
		"UPLOADER_TYPE" => "flash",
		"UPLOAD_MAX_FILE_SIZE" => "1024M",
		"USE_COMMENTS" => "Y",
		"USE_LIGHT_VIEW" => "Y",
		"USE_RATING" => "Y",
		"USE_WATERMARK" => "Y",
		"VOTE_NAMES" => array(0=>"1",1=>"2",2=>"3",3=>"4",4=>"5",5=>"",),
		"WATERMARK" => "Y",
		"WATERMARK_MIN_PICTURE_SIZE" => "200",
		"WATERMARK_RULES" => "USER"
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>