<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Фотогалерея события");
$APPLICATION->SetTitle("Фотогалереи");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:photogallery", 
	"custom", 
	array(
		"SHOW_LINK_ON_MAIN_PAGE" => array(
			0 => "id",
			1 => "shows",
			2 => "rating",
			3 => "comments",
		),
		"USE_LIGHT_VIEW" => "Y",
		"SEF_MODE" => "Y",
		"IBLOCK_TYPE" => "photogalleries",
		"IBLOCK_ID" => "41",
		"SECTION_SORT_BY" => "UF_DATE",
		"SECTION_SORT_ORD" => "DESC",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "desc",
		"PATH_TO_USER" => "",
		"SECTION_PAGE_ELEMENTS" => "15",
		"ELEMENTS_PAGE_ELEMENTS" => "50",
		"PAGE_NAVIGATION_TEMPLATE" => "",
		"ALBUM_PHOTO_SIZE" => "203",
		"THUMBNAIL_SIZE" => "203",
		"JPEG_QUALITY1" => "100",
		"ORIGINAL_SIZE" => "1024",
		"JPEG_QUALITY" => "100",
		"ADDITIONAL_SIGHTS" => array(
		),
		"PHOTO_LIST_MODE" => "N",
		"SHOWN_ITEMS_COUNT" => "",
		"SHOW_NAVIGATION" => "N",
		"DATE_TIME_FORMAT_DETAIL" => "d.m.Y",
		"DATE_TIME_FORMAT_SECTION" => "d.m.Y",
		"SET_TITLE" => "Y",
		"CACHE_TYPE" => "Y",
		"CACHE_TIME" => "3600",
		"CACHE_NOTES" => "",
		"USE_RATING" => "N",
		"SHOW_TAGS" => "N",
		"DRAG_SORT" => "Y",
		"UPLOADER_TYPE" => "form",
		"APPLET_LAYOUT" => "extended",
		"UPLOAD_MAX_FILE_SIZE" => "5",
		"USE_WATERMARK" => "N",
		"WATERMARK_RULES" => "ALL",
		"WATERMARK_TYPE" => "PICTURE",
		"WATERMARK_FILE" => "",
		"WATERMARK_FILE_ORDER" => "usual",
		"WATERMARK_POSITION" => "mc",
		"WATERMARK_TRANSPARENCY" => "20",
		"PATH_TO_FONT" => "",
		"WATERMARK_MIN_PICTURE_SIZE" => "800",
		"MAX_VOTE" => "5",
		"VOTE_NAMES" => array(
			0 => "1",
			1 => "2",
			2 => "3",
			3 => "4",
			4 => "5",
			5 => "",
		),
		"DISPLAY_AS_RATING" => "rating",
		"USE_COMMENTS" => "N",
		"COMMENTS_TYPE" => "blog",
		"BLOG_URL" => "util-photo-blog-s1",
		"COMMENTS_COUNT" => "10",
		"PATH_TO_BLOG" => "",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"NAME_TEMPLATE" => "#NOBR##LAST_NAME# #NAME##/NOBR#",
		"TAGS_PAGE_ELEMENTS" => "150",
		"TAGS_PERIOD" => "",
		"TAGS_INHERIT" => "N",
		"TAGS_FONT_MAX" => "30",
		"TAGS_FONT_MIN" => "10",
		"TAGS_COLOR_NEW" => "3E74E6",
		"TAGS_COLOR_OLD" => "C0C0C0",
		"TAGS_SHOW_CHAIN" => "N",
		"SEF_FOLDER" => "/photogalleries/",
		"COMPONENT_TEMPLATE" => "custom",
		"SECTION_LIST_THUMBNAIL_SIZE" => "70",
		"SEF_URL_TEMPLATES" => array(
			"index" => "index.php",
			"section" => "#SECTION_ID#/",
			"section_edit" => "#SECTION_ID#/action/#ACTION#/",
			"section_edit_icon" => "#SECTION_ID#/icon/action/#ACTION#/",
			"upload" => "#SECTION_ID#/action/upload/",
			"detail" => "#SECTION_ID#/#ELEMENT_ID#/",
			"detail_edit" => "#SECTION_ID#/#ELEMENT_ID#/action/#ACTION#/",
			"detail_list" => "list/",
			"search" => "search/",
		)
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>