<?
$aMenuLinks = Array(
	Array(
		"Образовательная и просветительская", 
		"obrazovatelnaya/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Научная и инновационная", 
		"nauchnaya/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Формирование культуры безопасности жизнедеятельности", 
		"/activity/formirovanie-kultury-bezopasnosti-zhiznedeyatelnosti/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Идеологическая", 
		"ideologicheskaya/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Международная", 
		"mezhdunarodnaya/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Издательская", 
		"izdatelskaya/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Спортивная", 
		"/activity/sportivnaya/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Технические комитеты", 
		"/activity/tekhnicheskiy-komitet-tk-by-35/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>